FROM registry.cn-shenzhen.aliyuncs.com/efucloud-public/nginx:1.29.4-alpine

ARG GIT_COMMIT
ARG BUILD_DATE

LABEL org.opencontainers.image.title=token-router-frontend
LABEL org.opencontainers.image.revision=${GIT_COMMIT}
LABEL org.opencontainers.image.created=${BUILD_DATE}

# 从 builder 复制构建产物
COPY ./dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
