export default [
  {
    path: '/',
    component: './index',
    layout: false,
  },
  {
    path: '/personal/dashboard',
    name: 'myDashboard',
    icon: 'DashboardOutlined',
    component: './dashboard/my',
    access: 'canUsePersonalConsole',
  },
  {
    path: '/personal/chat',
    name: 'modelChat',
    icon: 'MessageOutlined',
    component: './chat',
    access: 'canUsePersonalConsole',
    hideInMenu: true,
  },
  {
    path: '/personal/models',
    name: 'availableModels',
    icon: 'RobotOutlined',
    component: './models',
    access: 'canUsePersonalConsole',
  },
  {
    path: '/personal/tokens',
    name: 'apiTokens',
    icon: 'KeyOutlined',
    component: './tokens',
    access: 'canUsePersonalConsole',
  },
  {
    path: '/system',
    name: 'systemConsole',
    icon: 'ControlOutlined',
    access: 'canUseSystemConsole',
    routes: [
      {
        path: '/system',
        redirect: '/system/dashboard',
      },
      {
        path: '/system/dashboard',
        name: 'dashboard',
        icon: 'DashboardOutlined',
        component: './dashboard/admin',
        access: 'canUseSystemConsole',
      },
      {
        path: '/system/providers',
        name: 'providers',
        icon: 'CloudServerOutlined',
        component: './system/providers',
        access: 'canUseSystemConsole',
      },
      {
        path: '/system/channels',
        name: 'channels',
        icon: 'ApiOutlined',
        component: './system/channels',
        access: 'canUseSystemConsole',
      },
      {
        path: '/system/models',
        name: 'models',
        icon: 'RobotOutlined',
        component: './system/model-management',
        access: 'canUseSystemConsole',
      },
      {
        path: '/system/routes',
        name: 'routes',
        icon: 'BranchesOutlined',
        component: './system/routes',
        access: 'canUseSystemConsole',
      },
      {
        path: '/system/diagnostics',
        name: 'diagnostics',
        icon: 'ExperimentOutlined',
        component: './system/diagnostics',
        access: 'canUseSystemConsole',
      },
      {
        path: '/system/users',
        name: 'users',
        icon: 'TeamOutlined',
        component: './system/users',
        access: 'canUseSystemConsole',
      },
      {
        path: '/system/users/:id/dashboard',
        component: './dashboard/my',
        access: 'canUseSystemConsole',
        hideInMenu: true,
      },
      {
        path: '/system/usage',
        name: 'usage',
        icon: 'BarChartOutlined',
        component: './system/usage',
        access: 'canUseSystemConsole',
      },
      {
        path: '/system/attempts',
        name: 'attempts',
        icon: 'AuditOutlined',
        component: './system/attempts',
        access: 'canUseSystemConsole',
      },
      {
        path: '/system/audit',
        name: 'audit',
        icon: 'FileSearchOutlined',
        component: './system/audit',
        access: 'canUseSystemConsole',
      },
    ],
  },
  {
    path: '/oauth/login',
    component: './oauth/login',
    layout: false,
  },
  {
    path: '/oauth/callback',
    component: './oauth/callback',
    layout: false,
  },
  {
    path: '/dashboard',
    component: './index',
    layout: false,
  },
  {
    path: '/gateway/dashboard',
    redirect: '/personal/dashboard',
    hideInMenu: true,
  },
  {
    path: '/gateway/chat',
    redirect: '/personal/chat',
    hideInMenu: true,
  },
  {
    path: '/gateway/models',
    redirect: '/personal/models',
    hideInMenu: true,
  },
  {
    path: '/gateway/tokens',
    redirect: '/personal/tokens',
    hideInMenu: true,
  },
  {
    path: '/admin/dashboard',
    redirect: '/system/dashboard',
    hideInMenu: true,
  },
  {
    path: '*',
    component: './index',
    layout: false,
  },
];
